name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run Black formatter
      run: |
        black --check --diff debug_cli/ tests/
    
    - name: Run isort
      run: |
        isort --check-only --diff debug_cli/ tests/
    
    - name: Run flake8
      run: |
        flake8 debug_cli/ tests/ --count --statistics --max-line-length=88
    
    - name: Run mypy
      run: |
        mypy debug_cli/ --ignore-missing-imports
    
    - name: Run bandit security check
      run: |
        python -m bandit -r debug_cli/ -f json -o bandit-report.json || true
        python -m bandit -r debug_cli/
